### ISSUE TITLE
Client startup crash with liteloader

### ISSUE THREAD

**Issue by Dalethium** [mezz/JustEnoughItems#1189]
[Crash log](https://pastebin.com/jiFKvLiR)

Hey so, this version of jei (the latest beta released 12 hours ago) works just fine on the server I run, but starting up the client leads to a crash just before getting to the main menu. I am sure it's probably not a issue with just jei alone as nobody else has reported anything yet, however I figure it's worth reporting in case it's a easy fix without a bug hunt.

Thanks! Have a great day!~

**Comment by mezz** [comment]
Thanks for the report!
Can you try without liteloader installed? I'm curious to see if the error only happens when liteloader is there.

**Comment by Dalethium** [comment]
Yeah sure! Just one moment!

**Comment by Dalethium** [comment]
Sorry about the wait, I had some hard drive troubles!

You were right! Disabling lite loader allowed me to launch with no issue! 

Is there anything else you need?

**Comment by Dalethium** [comment]
I noticed this is still marked as "needs followup." Do you need anything else?

**Comment by mezz** [comment]
I tried to get in touch with the author of liteloader but wasn't able to.
I can try to work around this but I'm not really familiar with liteloader. Can you explain your setup a little bit so I can try to reproduce the issue?

**Comment by Dalethium** [comment]
Sure! I am using multi mc, the latest forge, along with the mods listed here: https://pastebin.com/kfTyFGxf

I uninstalled liteloaded for the duration, I was only using it for tabbychat. It launches just fine without it. 

The build 4.8.5.159 of jei works perfectly fine with liteloader, however later builds (4.9+ for sure) do not - including the current stable build.

Let me know if you need anything else! Thanks.

**Comment by mezz** [comment]
Thanks, I tried to replicate this but surprisingly didn't crash.
I need some more information to solve this issue, can you please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here?

**Comment by Dalethium** [comment]
Hey so it spams for nearly every recipe in the game or something so the log is nearly 100mb, I had to upload it zipped instead. 

[Onedrive](https://1drv.ms/u/s!AhVEqOwQ4svJglg1K7Llk12UTWVT) 

Let me know if there's anything else!

**Comment by mezz** [comment]
Thanks for the log. I looked it over and what I see is really bizarre.
I'll try to find some more time to replicate the issue, I probably need to add more logs in some obscure places to see what's really breaking.

**Comment by ZeldaLinkAaron** [comment]
So I was having a similar problem with SevTech 3.0.6 and I tried downgrading to "1.12.2-4.8.5.159" which worked. But when I was playing with it and made a new environment with just Forge, JEI, and Liteloader, the newest version worked which made me thing it must have something to do with one of the other mods.

**Comment by mezz** [comment]
Can you try to narrow down which mod is causing an issue?

**Comment by Dalethium** [comment]
Hey! So I am not currently playing minecraft, but I figured I'd compile you a list of the mods we have in common [right here](https://pastebin.com/sJKkZbu9)

It's off the top of my head, and i certainly missed some libraries on the list, but I hope it helps :)

**Comment by johnfriedrich** [comment]
Same? crash: https://pastebin.com/kui9QLaz
Started when updating our launcher from
jei_1.12.2-4.8.5.147.jar to jei_1.12.2-4.9.1.188.jar
(At least at this point many reports from users started to come in, that reported these crashes)

Our server disabled some recipes by overwriting them with empty dummy recipes. That miiiight be the cause.
Thats our empty dummy recipe that overwrites unwanted recipes:
http://prntscr.com/jnrrq5

I mean they crash before they are able to login to the server, but maybe JEI caches data from last session?

**Comment by MoJoCreatior** [comment]
a temporary solution to this issue is to downgrade JEI version to 4.8 or anything below 4.9

note: the JEI plugin for pams harvest craft needs to be disabled as it requires JEI 4.9+

something that changed between version 4.8 and 4.9 is conflicting with liteloader, currently it's unknown whether it's liteloader or JEI that's initially causing the issue.

I'll edit this comment with any new testing results, but it seems to be working fine for now. time will tell

**Comment by mezz** [comment]
Between those versions of JEI I fixed an issue where JEI ignored all resource reloads before entering a world.
This was a problem when players changed their language in the main menu. JEI needs to respond to that and reload so that it is searching in the right language.

The issue here is related to the fact that LiteLoader forces an extra resource reload during startup.
However, I have tested with JEI and LiteLoader alone and didn't encounter any issues.

Somehow, some extra thing (a LiteLoader mod?) in combination with the extra resource reload from LiteLoader is really killing JEI and causing the issue we see here.

I need help narrowing down the combination of things that causes this issue so that I can test and fix it.
So far I have a very long list of suspected mods. In order to effectively debug this I will need to know the minimum setup to reproduce this issue. If anyone here can help with that, it would be appreciated.

**Comment by Routhinator** [comment]
@mezz I just hit this issue and found this. I only had one liteloader mod installed which was WorldEditCUI. I removed it after reading this and the game still failed to load. So it's not a liteloader mod.

**Comment by ghost** [comment]
Had this problem on a completely different setup.... but removing FastWorkbench fixed the issue.

**Comment by Supermario1313** [comment]
[Here's my crash report.](https://gist.github.com/Supermario1313/e0c6b0494c7b18cd353edede67ca8f55)
I'm using Minecraft 1.12.2 with Forge 14.23.4.2727 and LiteLoader 1.12.2-SNAPSHOT. My launcher is MultiMC.
Thanks to this, @Dalethium's list of mods we have in common can be narrowed to these mods:
- Applied Energistics 2  
- AutoRegLib
- Baubles
- BiblioCraft  
- CodeChickenLib
- Ender Storage 1.8.+
- ExtraPlanets  
- Forge MultiPart CBE  
- Galacticraft (Core + Planets)
- HWYLA
- Industrial Foregoing
- Inventory Tweaks  
- Iron Chests
- Just a Few Fish  
- Just Enough Items (JEI) 
- Mantle
- MicdoodleCore
- MJRLegendsLib
- Quark
- Shadowfacts' Forgelin
- TeslaCoreLib
- The Twilight Forest  
- Tinkers Construct

I wasn't able to reproduce the crash in a fresh installation of Mincraft 1.12.2 with only Forge 14.23.4.2727, LiteLoader 1.12.2-SNAPSHOT and the above mods. However, removing [Redstone++](https://minecraft.curseforge.com/projects/redstoneplusplus) 1.2d or 1.3 BETA-2 (These two versions generate the same crash report) fixed the issue for me whereas downgrading JEI to 4.8 like @MoJoCreatior suggested didn't fix it.

I was able to reproduce the crash in a fresh installation of Mincraft 1.12.2 with only Forge 14.23.4.2727, LiteLoader 1.12.2-SNAPSHOT and Redstone++ 1.3 BETA-2, giving [this crash report](https://gist.github.com/Supermario1313/4720ab57b04fb60323c49d4c001846b9). I got the same result with Redstone++ 1.2d instead of Redstone++ 1.3 BETA-2.

Since @Dalethium had this problem without Redstone++ installed, this means that the crash wasn't caused by a specific mod, but by a behaviour used in multiple mods.

**Comment by mezz** [comment]
I think there may be multiple issues happening in this thread.

For things involving FastWorkbench, Inspirations, DietHopper, and other mods that use Forge Registry replacement (there are a lot), I investigated the problem and submitted an issue to LiteLoader here:
http://develop.liteloader.com/liteloader/LiteLoader/issues/53

Once that's fixed, hopefully what's happening here should be more clear.

**Comment by Iomega0318** [comment]
Just chiming in as I was having the same issue and wanted to do a little digging, I play on a Continuum Server and was wanting to install Tabby Chat, after getting the error I found this thread.

Mod Pack:
https://www.feed-the-beast.com/projects/ftb-continuum

I disabled FastWorkbench first as I was going to go down the list and see what was causing the issue, after disabling FastWorkbench I was able to load the pack just fine, DietHopper is also installed but did not need to be disabled.

Unfortunately in order to play the pack I need it enabled, so going to rollback JEI for now and see if that works.


**UPDATE**
Can also confirm rolling JEI (and JEHC) back seems to allow it to load, granted I had to roll back to v4.8.5.159.. I am logged in and using TabbyChat/Liteloader in the mod pack now.

**Comment by ghost** [comment]
bad bot

**Comment by Tkain** [comment]
very bad bot, this isn't even solved

**Comment by Brycey92** [comment]
@mezz Please reopen this. Thanks!

**Comment by mezz** [comment]
I was on vacation so this went stale, reopening.

**Comment by Brycey92** [comment]
Is there a way to prevent the bot from marking this issue as stale and closing it?

**Comment by ghost** [comment]
nuke the bot from orbit

**Comment by mezz** [comment]
The bot is useful in general, this is a rare issue where it's just not getting fixed.
I think Mumfrey (author of LiteLoader) is just not active any more, the last commit there was 10 months ago.

**Comment by Brycey92** [comment]
Unfortunately, despite liteloader being open source, Mumfrey has licensed it as All Rights Reserved, and required written permission for anyone to distribute modified versions of the mod. A maintenance programmer would have to get in touch with Mumfrey before there can be any hope of having this issue fixed. That, or of course Mumfrey himself would have to return to developing, but that seems very unlikely.

**Comment by Vitali8** [comment]
I got [this crash](https://paste.dimdev.org/dalatenedo.mccrash) (with `java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.item.ItemStack`) after loading the client with the LiteLoader, Forge 2796+ and some modpack (~90 mods). But if I reduce the number of mods I start to get crash with `java.lang.IllegalArgumentException: recipeCategories must not be empty.` And of course if I remove the LiteLoader, then no crashes happens.

**Comment by ConnorTron110** [comment]
For me I managed to fix the issue by removing fast workbench (i dont think its liteloader due to me still having voxel maps installed, but if its a certain liteloader mod then ok....).

**Comment by mezz** [comment]
I believe the issue is related to LiteLoader breaking when Forge mods replace vanilla items (for example FastWorkbench replaces the vanilla crafting table).

I reported the issue to LiteLoader with a minimal test mod that shows the issue: http://develop.liteloader.com/liteloader/LiteLoader/issues/53
Unfortunately it has been open for 6 months, and I do not think LiteLoader is being actively maintained any more.

**Comment by ghost** [comment]
I'd drop Liteloader... but worldeditcui and tabbychat :(

**Comment by Brycey92** [comment]
@steamp0rt I don't have a solution for tabbychat, but I present to you [WorldEditCUI Forge Edition 2](https://minecraft.curseforge.com/projects/worldeditcui-forge-edition-2?gameCategorySlug=mc-mods&projectID=261019)

**Comment by ghost** [comment]
@Brycey92 does it work with the GriefProtection plugin? I noticed the LiteLoader version shows GP plot boundaries.

**Comment by Brycey92** [comment]
@steamp0rt I've never noticed either version showing GP plots, though I haven't used the Forge WE-CUI with GP yet. I always just rely on the glowstone and gold borders done by GP itself. If you could test the cross-functionality, though, I'd be interested in knowing the answer!

**Comment by ghost** [comment]
I'm using the LL version and it shows the plots if I right click with a stick

**Comment by mezz** [comment]
Please keep discussion here focused on the bug.
If you would like somewhere to meet up and discuss, feel free to join the general channel on my discord here: https://discord.gg/DDrCEQH

**Comment by Graywaren** [comment]
Has there been any progress on this bug? I too am having this issue and am solely trying to get LL to work with my pack for Voxel Map. I disabled fast work bench and got it to load at least, but I'd really like to be able to use FWB. I'm also concerned that as I get further in the modpack I'm developing something else that replaces a vanilla item (if that's what's causing the problem?) will end up crashing it in future.

**Comment by mezz** [comment]
Please see this comment, unfortunately there haven’t been any updates since then: https://github.com/mezz/JustEnoughItems/issues/1189#issuecomment-453878592

**Comment by TwinQuicksilver** [comment]
I have been crashing on start up all evening and have been eliminating mods one by one. The only thing that MC's crash reports is finding an issue with is JEI. I never heard of LiteLoader before reading this thread so I was surprised to learn World Edit was being maintained by Mumfrey. So I began deleting my mods until my list went from 71 to 62 and I started with the mods everyone on this thread began to remove first. The full list of mods I removed were:

- Actually Additions
- Astral Sorcery
- Biomes You'll Go
- Buildcraft
- ChanceCubes
- CookingForBlockheads
- Decocraft
- OpenBlocks
- ThaumicTinkerer
- TwilightForest
- WorldEditCUI

The crash occurred every time I loaded up making it so I never got to the actually menu for the game. I haven't checked through all of the mod lists that have been shared, but if any of your mods have been managed my Mumfrey and are LiteLoader affiliated I'd assume get rid of them. It was an instant fix on my end and the game runs fine, but I haven't tested to see if readding any of those mods will crash me. (Yet) I figured because my list of removed mods was small it may help isolate the issue. I will share what my original list of mods was soon anyways, just getting called to dinner currently and I don't know how long that will take or if anyone will need me for anything afterwards. 

Hopefully this helped in some way. Cheers!

**Comment by asiekierka** [comment]
@tommyTT, this one's for you.

## Diagnosis

As an early user of registry substitution who ran into many bugs with the feature, I knew it relies on the ObjectHolder mechanism. ObjectHolders are a hacky system fo͜r͠ su̡bs͜t͝i͝túti͟ņg҉ ̛s͠tati͡c ̢f̶iel͠d r̀e͡ference҉s w̦̼h̯̀il̢̗͓è̱̮̫̯̭ ̣̼̺̻͙̜n̴̜͙͙̜̫ǫ̘͉͕̜̟ț̘͙̻͎͜ ̝͓̹͓̳̩̫b̡̭̥̥̳̰͔͎r̰̰̪e̹͝a̭k̕ì̯̘̗̟̦̞ͅn̢̻͎g̮̙͎͖̤̝̀ͅ ̬v̢̫̼̲a̭̹̩̲̟n͚͉̪͝Z̧̛͍̻̦A̸̸̩͚̫͙͉͎̖̹͚͇̲͔̹̱L̨̨̝̬̰Ǵ̸̦̣͚̲͇͚̜͉̕͟O̶͏͏̛͇̦̖͉̤̹̺͈̺̺̩͙͖̹͙̲͢ͅ ͙̞͓̠͚͕̕ͅH͏̨͖̗̟͙͖̭͝Ḛ̦̘͕̻͙̘̲̹͚̥͈̣̗̝̣̞̜̝͘͟͜͞ ̶̷̨̛̙̦̼̝̞̭̲̖͚̼͖C̷̢̼͎͉̲̤͓̮̲̣̕ͅÒ̹͖͉̞͈̞͔̹̳̟̭̝̘̲̘̰̰̘͘͘͞M̴̖̝̗͚̻͇̩̮͈͉̪̣͎̯͓͞E̕̕͟͏͈̟̳͇̞̯̰̳̖Ş̵̶̢̢̹̖̩ Either way, Forge allows mods to utilize the feature themselves by using the "@ObjectHolder" annotation, as well as hooking the static fields in key areas (net.minecraft.init) by itself. Failing to replace one of those key areas would led to the Block or Item instance in it to differ from the one in the registry, causing some serious !? - which we are observing here.

The next observation is by checking the game's log. In a LiteLoader-free environment, 1168 ObjectHolder annotations will be observed. In one with LiteLoader, only 705 can be seen - and the missing ones happen to be all of the field references to the Blocks and Items classes, causing... registry subsitution issues in Blocks and Items.

The code for scanning classes for applicable non-annotated fields (as would be the case in net.minecraft.init.Blocks) looks as follows (with uninteresting parts stripped for simplicity):

```java
        for (Field f : clazz.getFields())
        {
            int mods = f.getModifiers();
            boolean isMatch = Modifier.isPublic(mods) && Modifier.isStatic(mods) && Modifier.isFinal(mods);
            if (!isMatch || f.isAnnotationPresent(ObjectHolder.class))
            {
                continue;
            }
            addHolderReference(...);
        }
```

As you can see, there are two requirements for a match:

* the field must be *public*, *static* and *final*,
* the field must *not* have an ObjectHolder annotation (which it won't, as that annotation is added by Forge; this is to prevent duplicate holder references from being added by earlier-running code scanning annotations).

Of course, the Blocks and Items class have public, static, final block/item fields - normally. LiteLoader strips the "final" part of the fields' modifiers, making the match fail and the object holding to not be applied - which means that registry substitutions will not work correctly.

We can see that this is a deliberate operation on LiteLoader's part in its class transformer:

```java
        else if (Obf.Blocks.obf.equals(transformedName)
                || Obf.Blocks.name.equals(transformedName)
                || Obf.Items.obf.equals(transformedName)
                || Obf.Items.name.equals(transformedName))
        {
            return this.stripFinalModifiers(basicClass);
        }
```

## Wait a minute, WHAT?

Why is LiteLoader doing this?

[The commit which introduces the feature](http://develop.liteloader.com/liteloader/LiteLoader/commit/3e955ef14767cfd7d077ef86c2f00db1cdce761e.diff) also adds a method called ModUtilities.addBlock, providing a similiar - if more rudimentary - means of registry substitution.

Curiously, however, the feature was removed in a ["Quick and dirty 1.10 update"](http://develop.liteloader.com/liteloader/LiteLoader/commit/fd2df210fcdc89137c8b3d847f42146f4121ab3c) with little to no fanfare. The coremod patch, however, persists.

## What can we do about this?

Well...

* We could coremod Forge. But then someone would probably yell at me. Not an option.
* We could coremod LiteLoader. Except we can't, because transformers are generally exempt from being coremodded themselves.
* We could write a coremod which runs just after LiteLoader and undoes its patch, then release it as a mod. *Perfect.*

So I've made a mod!

* [Download here](https://asie.pl/files/mods/ExtraFoamForLiteLoader)
* [CurseForge link](https://minecraft.curseforge.com/projects/extra-foam-for-liteloader) - as of writing, not accepted yet

Oh, wait, it's 2:30 AM. See you~

**Comment by mezz** [comment]
I am closing this issue because this bug is not getting fixed in LiteLoader, and asie has provided a workaround mod here: https://github.com/mezz/JustEnoughItems/issues/1189#issuecomment-498078956
