### ISSUE TITLE
API: Game crashes when opening inventory

### ISSUE THREAD

**Issue by Brickmotion** [mezz/JustEnoughItems#1190]
I am a mod developer intending to put JEi support into my mod. Therefore, I installed the API, following this tutorial: [https://www.youtube.com/watch?v=Y-IF8gQwWGI](url)

However, the API for some reason doesn't seem to work. Even without making any API-related alterations to the code (meaning right after installation), the game seems to start without any problems, yet once I attempt to open the game inventory, the game crashes.

The crash report always shows the same type of error: "_Rendering ingredient java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.RenderItem.renderModel(Lnet/minecraft/client/renderer/block/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V from class mezz.jei.render.ItemStackFastRenderer_"

I couldn't find anything online as to how to fix this issue, nor could I resolve it myself. The tutorial I used somehow doesn't seem to have this problem, despite doing the exact same thing as I did.

I hope someone knows what causes this issue, and how I might resolve it.

**Comment by insuusvenerati** [comment]
Having the same issue. After speaking with Mezz on discord we figured out it was caused by a change in forge. To work around the issue, switch your project to forge version 1.12.2-14.23.2.2654

**Comment by mezz** [comment]
Thanks for the report!
I'm working on a fix for this in Forge today, it's a bit complicated.

**Comment by mezz** [comment]
This is fixed with the latest ForgeGradle.
You will need to run gradle with `--refresh-dependencies` to make it update ForgeGradle in your project.

**Comment by vinz243** [comment]
Hello, I tried with forge 14.23.2.2654 and I still get the crash... I'm using ForgeGradle 2.3

**Comment by mezz** [comment]
@vinz243 this issue is over a year old, please open a new issue with your crash log.
