### ISSUE TITLE
[1.10.2] Disable Item Cheating on a Server

### ISSUE THREAD

**Issue by Achim-Sommer** [mezz/JustEnoughItems#1226]
How i can disable the Item Cheating mod on my Modpack Server?

The player can not use the command /give.

But the player can set the Item Cheating mode to true. And can take any Item.

**Comment by mezz** [comment]
JEI does this check on the server. If the server sees that they are in creative, or if it sees that they can `/give` themselves a stack of nether stars, it will allow them to cheat.

Note that some permission mods may change who can use `/give` or break it in an unexpected way.

**Comment by Achim-Sommer** [comment]
Nobody can use /give.
But everybody can use the Item Cheating Mode.

**Comment by mezz** [comment]
Are you running any mods that might change the way permissions work for `/give`?

**Comment by Achim-Sommer** [comment]
no. Only ForgeEssentials. But nobody had the permission command.give

**Comment by mezz** [comment]
Is there somewhere I can download a pack or join, to debug the issue?

**Comment by Achim-Sommer** [comment]
[GermanGaming Community-1.06.zip](https://github.com/mezz/JustEnoughItems/files/1998029/GermanGaming.Community-1.06.zip)
Import this into the Twitch Desktop App.

Mods --> create Profil --> import

**Comment by mezz** [comment]
Thanks. Please whitelist the player name "mezz" for your server.

**Comment by Achim-Sommer** [comment]
You are on the Whitelist now

**Comment by mezz** [comment]
I have just released JEI `3.14.8.422` for 1.10.2. It now has the same permissions logic as the 1.12.2 version.
Please add it on your server and see if that fixes the issue.

**Comment by Achim-Sommer** [comment]
No i can still get the Item Cheating mode. And I get the Items. I dont understand this becasue /give is not working. And /gamemode 1 also not working.

**Comment by mezz** [comment]
Please try without ForgeEssentials, it is the only thing I see that might cause an issue.

**Comment by Achim-Sommer** [comment]
Yeah with ForgeEssentials its work. But why when nobody had the permsission for /give

**Comment by mezz** [comment]
Unfortunately I don't know how their mod works, it is some kind of bug with ForgeEssentials.

**Comment by mezz** [comment]
I think what probably happens is this:
1. You ask if you can `/give` and ForgeEssentials says "yes".
2. You try to actually use `/give` and ForgeEssentials gives an error if you do not have permission.

JEI only does 1. After that it uses its own code to give the item.
I am not sure why ForgeEssentials would do it that way, I think it is not the correct way.
