### ISSUE TITLE
(1.13.2) JEI NoSuchMethod errors in dev environment

### ISSUE THREAD

**Issue by TyrellPlayz** [mezz/JustEnoughItems#1511]
I'm getting errors like this when trying to load JEI in my IDE
https://gist.github.com/TyrellPlayz/a04b285f138a9f3baf2dd68ffd54b5fc

**Comment by mezz** [comment]
Thanks for the report!
I tried it out and got the same error.

**Comment by mezz** [comment]
This seems to be an issue with the options we have for setting up mod dependencies in ForgeGradle.
I can't really get deobfuscation using gradle to work, and the runtime deobfuscation for mods in the `mods` folder has been removed in 1.13.

**Comment by KnightMiner** [comment]
Does it still work with the libs folder? That's the way I typically add non-maven dependencies. I don't recall whether that deobfuscates or just copies to the mods folder

**Comment by Tamaized** [comment]
Using `https://dvs1.progwml6.com/files/maven/` as the maven url seems to work with `deobf`, at least for me.

https://github.com/MinecraftForge/ForgeGradle/issues/571#issuecomment-473668106

**Comment by mezz** [comment]
Confirmed that adding a trailing slash to the repository url makes `deobf` work. Thanks!

**Comment by mezz** [comment]
I have submitted a fix for the maven url issue to ForgeGradle here: https://github.com/MinecraftForge/ForgeGradle/pull/576

**Comment by mezz** [comment]
I made cpw aware of the AT issues and he will look into them when he finds some time to (probably in the next few weeks).

**Comment by TyrellPlayz** [comment]
Still having issues here's some more information.
[build.gradle](https://gist.github.com/TyrellPlayz/886c034c30fae05d159a9ebe6fa967b6)
[error log](https://gist.github.com/TyrellPlayz/5fa33292d9834195c4fd63842449e591)
![image](https://user-images.githubusercontent.com/19235911/54579020-938fec00-4a51-11e9-8546-cc2abecd39b8.png)

**Comment by mezz** [comment]
Please try with the version released today and see if it has fixed the issue.

**Comment by mezz** [comment]
Having some issues with the build servers but I will try to get a potential fix for this out soon.

**Comment by mezz** [comment]
Please try with JEI version 5.0.0.11, it should be fixed.

**Comment by TyrellPlayz** [comment]
Still getting the same error. I think it's something on forges side or something wrong with my setup.
https://gist.github.com/TyrellPlayz/66f2b7ee315460e2f3a5c728e21b6494

**Comment by mezz** [comment]
Hmm, thanks. 
It's working for players now, but Forge is still missing something that lets ATs from other mods work in the developer environment.

**Comment by TyrellPlayz** [comment]
Well that's nice. I thought I would need to add it to my AT for it to work but don't have a full understanding of how to add to the AT.

**Comment by mezz** [comment]
The hacky workaround for now is to just copy everything from JEI's file AT into your AT file, then refresh your project so they get applied. 
You can find JEI's AT file here: https://github.com/mezz/JustEnoughItems/blob/1.13/src/main/resources/META-INF/accesstransformer.cfg

**Comment by TyrellPlayz** [comment]
Didn't work, got the same error

**Comment by mezz** [comment]
You may not have set up the dependency correctly, you will want to use `deobf` like this:
`deobf "mezz.jei:jei-${project.mcversion}:${project.jeiversion}"`

**Comment by TyrellPlayz** [comment]
`deobf "mezz.jei:jei-${project.minecraft_version}:${project.jei_version}"`
did not work
Here's my [build.gradle](https://github.com/TyrellPlayz/Big-Industries/blob/dev/build.gradle) if you want to look

**Comment by mezz** [comment]
Leave out the `compile` line entirely for now and if you crash, please paste the new crash log to gist and link it here.

**Comment by TyrellPlayz** [comment]
That worked
