### ISSUE TITLE
[1.20.1] Not saving hidden state of JEI across launches

### ISSUE THREAD

**Issue by MarioSMB** [mezz/JustEnoughItems#2296]
Using CTRL+O to hide the JEI inventory item list does not persist, causing it to reappear when restarting the game. This did not occur in earlier (1.12.2) versions of the mod, causing some frustration as one needs to hide it again every single launch.

**Comment by mezz** [comment]
Thanks for the report!
This is fixed in the latest versions of JEI for 1.16, 1.17 and 1.18.
You can bind a hotkey to toggle the "hide items" mode on and off in the Minecraft controls, and the hidden items will stay hidden properly.

**Comment by MarioSMB** [comment]
This does not appear to be resolved in 1.18.2 versions of the mod; the item list pops up again after each launch.

**Comment by MarioSMB** [comment]
Hey... any updates on this? It's still happening in 1.20.1, 3 years later...

**Comment by anoomolu** [comment]
Would like to bump this, I'm unable to keep JEI hidden by default after relogging

**Comment by MarioSMB** [comment]
@mezz Pardon the ping, but I would like to kindly ask that you please look into this problem again.  

Some people like to have JEI to see uses and recipes for items, not for the cheat sheet that pops up every time the game is opened, so making it stay closed across game launches when toggled off would be very much appreciated.

**Comment by MarioSMB** [comment]
Apologies for another bump, but we seem to have ticked over to a new year with this bug still present.  

I would be very grateful if you could please take some time to look into this bug and why it returned, thank you!
