### ISSUE TITLE
Ghost ingredient handlers leave ghosts

### ISSUE THREAD

**Issue by uecasm** [mezz/JustEnoughItems#2437]
Originally observed in JEI 1.16.5-7.6.4.90, but still present in 1.16.5-7.7.1.116.

* When clicking on an item in the JEI right-hand panel with a GUI open that has an `IGhostIngredientHandler`, simple clicking tries to start a drag operation instead of opening the recipes for the clicked item as normal.  A click-and-release should behave as normal and the drag should only start on click-and-drag more than a small threshold distance.

* When hovering an item in the right panel in the same circumstances, JEI shows green highlights in the slots where that item can be dragged to.  This is fine.  But then when pressing R/U on the item to show the recipe GUI, the green highlights continue to be visible on top until the mouse is moved to highlight a different item.  It should clear the highlights as soon as the GUI changes.
    ![image](https://user-images.githubusercontent.com/539951/127858658-d82adbae-1cf4-43e3-a8fe-aa39a256de84.png)

**Comment by mezz** [comment]
Thanks for the report!

**Comment by mezz** [comment]
I think these issues should be fixed now, can you confirm?

**Comment by uecasm** [comment]
As of JEI 1.18-9.0.0.40 at least, the first appears fixed but the second still happens.  Is there a later version that you were expecting both would be fixed in?

**Comment by mezz** [comment]
The latest version of JEI is 9.1.2.61, but I think there haven't been any relevant fixes since the version you tried.
Thanks for confirming there is still a bug, I'll post back here when I get a chance to fix it.

**Comment by mezz** [comment]
This is fixed in the latest version of JEI for 1.18

**Comment by uecasm** [comment]
Thanks.  Will it be backported to 1.16 too or is that dead now?

**Comment by mezz** [comment]
Sure thing, I can still backport most fixes to 1.16.
Just pushed the fix, it should be available shortly.
