### ISSUE TITLE
[Bug]: Error log saying "Failed to load blacklist from file"

### ISSUE THREAD

**Issue by uhloin** [mezz/JustEnoughItems#3079]
### Steps to Reproduce the Bug

Just launch game

### Expected Behavior

No exceptions in the log

### Actual Behavior

Exception:
[09:51:32] [Render thread/ERROR] [me.je.li.co.EditModeConfig/]: Failed to load blacklist from file C:\Users\xen\AppData\Roaming\.minecraft\config\jei\blacklist.cfg
java.nio.file.NoSuchFileException: C:\Users\xen\AppData\Roaming\.minecraft\config\jei\blacklist.cfg
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?] {}
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?] {}
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?] {}
...

**Comment by mezz** [comment]
Thanks for the report!
Can you include the full error message? A lot of it is missing here.

**Comment by uhloin** [comment]
[
[stdout.log](https://github.com/mezz/JustEnoughItems/files/10453842/stdout.log)
](url)

**Comment by mezz** [comment]
Thanks!
This should be fixed in the latest version of the mod, can you try it out and see?

**Comment by uhloin** [comment]
Sorry but I cannot install 1.19.3 for my set of mods. For latest version in 1.19.2 error is still there
(jei-1.19.2-forge-11.5.2.1006.jar / forge-1.19.2-43.2.3-installer.jar / Minecraft 1.19.2)

To remove it I just created empty file but if I remove file, the exception returns.
See attachment
[latest.log](https://github.com/mezz/JustEnoughItems/files/10461628/latest.log)

**Comment by mezz** [comment]
Ok thank you for confirming the issue still exists on the latest 1.19.2 version at least, I will take a look soon.

**Comment by uhloin** [comment]
Thank you, exception is fixed:
[20Jan2023 10:30:12.186] [Render thread/DEBUG] [mezz.jei.library.config.EditModeConfig/]: Saved blacklist config to file: C:\Users\xen\AppData\Roaming\.minecraft\config\jei\blacklist.cfg
