### ISSUE TITLE
[Crash]: Too many catalysts crashes the client.

### ISSUE THREAD

**Issue by Darkhax** [mezz/JustEnoughItems#3183]
### Steps to Reproduce the Crash

Having too many recipe catalysts registered will cause the client to crash when accessing that category. This situation can be easily achieved when registering all the variants of a different catalyst, for example different wood type crafting tables or dyed variants of a catalyst.

### Extra Notes (Optional)

This crash occurs on both Forge and Fabric, and goes back to at least 1.18.2.

We discussed this issue a bit on Discord but I forgot to open an issue here. I ran into this issue when trying to add support for Botany Pots which has 98 catalyst variants that I would like to register. It has so many catalysts because there are 17 terracotta variants, 16 glazed terracotta variants, 16 concrete variants, and each of those has a hopping/non-hopping sub variant. This issue would also be encountered if mods reliably registered their crafting table variants as catalysts as well.

### Crash Report

https://gist.github.com/Darkhax/7a62f53180a2ddeafbb374a122ba46e7

**Comment by mezz** [comment]
Thanks for the report!
I pushed a change that should fix the issue, please test it out and let me know if anything else crashes.
With these changes, catalysts GUI should just extend off the screen. Ideally I should improve the UI for this case in the future, but at least it shouldn't crash any more.

**Comment by Darkhax** [comment]
@mezz Was this fix in 3.1.0.5? I am still getting the same crash on Forge and Fabric using this build.
[crash-2023-04-16_23.20.37-client.txt](https://github.com/mezz/JustEnoughItems/files/11246483/crash-2023-04-16_23.20.37-client.txt)

**Comment by mezz** [comment]
Thanks for letting me know, it looks like there are additional issues.
I will test by adding a lot of catalysts next time to verify it myself before pushing a fix.

**Comment by mezz** [comment]
This should be fixed now, I tested it out by adding 300 catalysts and they just extend off the screen now.
