### ISSUE TITLE
[Other]: JEI not showing item

### ISSUE THREAD

**Issue by tueure** [mezz/JustEnoughItems#3350]
### JEI no showing item

JEI don't show  items from a mod but show the rest the mod in question is " refined pipes" and the items " item pipe" version 1.16.5

**Comment by Alonlystalker** [comment]
Same here, some items from mods doesnt show up in jei, after each game reload it doesnt show different items, for me it's about half of the "create" blocks\items most of the time. i'm on 1.20.1

**Comment by JulesDeLaT-ITESM** [comment]
Me too, sudenly stopped showing items when searching, not sure if it is integration with other mods or anything like that but it does stop showing a ton of blocks, also on 1.20.1

**Comment by taj1994** [comment]
Similar issue here, except it's with enchanted books. JEI is only showing the max vanilla level for anything I search, and nothing lower (from vanilla), or higher (from mods, like Apotheosis). For example, if I search for Fortune, it only shows Fortune III, not I or II, or Unbreaking III, and not I or II, Protection IV, and not I, II, or III, etc.

First noticed in All the Mods 9, but also tested in an instance with just JEI installed. Test with:

Forge v47.1.3 (same version that ATM 9 uses) and Forge v47.2.1 (newest as of this comment)
JEI v15.0.2.27 (also newest as of this comment)

**Comment by SklxHero** [comment]
my JEI stopped working as it hadn't been installed, I already uninstalled the game, the mod, when I changed the version it worked, when I removed half of the mods it worked, there must be some mods that are buggy in the JEI in 1.16.5

**Comment by RionEV** [comment]
Confirmed independently.

Possible workaround: in `ingredient-list-type-sort-order.ini`, move Minecraft to the bottom of the list. 

My searchable page count increased from 66 pages to 69 pages in the instance I run. All items missing that I had noticed were not visible appear to be back now. Mod list and versioning available on request. Issue observed running Rubidium and Oculus. Had same issue as Alonlystalker above, based on given description.

Edit: After further testing, this only restores *some* of the lost or missing items. Others remain unavailable.

**Comment by iceystreeeeet** [comment]
@mezz do we have any updates on this issue?

**Comment by Gantros** [comment]
I am experiencing this issue as well, primarily with Create.

**Comment by Yovez** [comment]
I'm also experiencing this issue with Create.

**Comment by semenishchev** [comment]
Same issue with Create

**Comment by PIKO8** [comment]
The same problem with Create

**Comment by nicolobartolinii** [comment]
Same issue with Create. Sometimes I can't see some items from Create, other times (after game reload) I can't see other items.

Playing on 1.20.1 (server). JEI version: jei-1.20.1-forge-15.2.0.27

**Comment by AlexGuignard** [comment]
will this be fixed /worked on or is it already beeing investigated or smth issue is still active... ?

**Comment by Fireshark112** [comment]
Same for me, 1.20.1

**Comment by Fireshark112** [comment]
Sorry for my English, I'm using a translator. It’s strange, but I just fixed this bug by disabling all modes related to optimization like Rubidium, canary and everything began to display normally. A little later I’ll tell you more specifically which mod interfered
P.S interesting, but some mods simply remove items from create even from the creative menu, for example, FTB chunk, FTB Library. The reason is not clear. Deleting them helps a lot

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately there are many different underlying bugs being reported here at once and not enough information to take action.

* If you have an issue with a specific mod like Create: 
  * It is most likely a problem with the specific mod's JEI plugin. Please report to them.
  * If needed, the other mod's devs can ping me in their issue I can help them debug or resolve the problem.
* If you have a general issue with JEI not working correctly or items missing across many mods: 
  * It is probably due to a conflict with another mod, often a "performance" type of mod that makes broad changes.
  * Please try removing mods until the issues goes away, in order to identify which mod was causing the problem. 
  * You can report to that mod and report to me too. In your report, include a link to the other mod's issue, and I can help debug or resolve the problem.

**Comment by VolcanicMG** [comment]
For anyone still having issue with getting create working with JEI in 1.20.1 try disabling ModernFix. Can't say i'll work for all other mdos but it worked for me so thought i'd share. Like mezz said, it has to do with the way performance mods make changes to the way things are loaded in order to "Improve" load times.

**Comment by BenBeary** [comment]
> For anyone still having issue with getting create working with JEI in 1.20.1 try disabling ModernFix. 

If you want to keep the mod going, in the config the feature that is messing with JEI is called

**mixin.perf.blast_search_trees**
