### ISSUE TITLE
[1.10.2] Connection to the server is taking too long time.

### ISSUE THREAD

**Issue by mrapplexz** [mezz/JustEnoughItems#353]
Hello! Connection to my server is taking too long time when JEI installed. Server just kicks me after 30 seconds of logging in. I can join the server on the second try, my friend can join on the fourth try. My log: [click](http://pastebin.com/fACCHBjj), my modlist: [click](http://pastebin.com/qCW1JJzu).

**Comment by mezz** [comment]
Thanks for the report!
I can see three things in the log.

First:
`[Client thread/ERROR]: Failed to register mod plugin: class crazypants.enderio.jei.JeiPlugin`
Please make sure to  report that to EnderIO's github issue tracker, with the full log like you did here.
I don't think it's causing you to time out, but it is a problem.

Second thing is probably causing you to time out: 
`agriculturalexpansion` has many many broken recipes.
Try removing that mod and see if you can log in.
This may be a JEI issue with slow logging.

Lastly, there are several severe errors at the end of the log that are not related to JEI:
`java.util.concurrent.ExecutionException: java.lang.NullPointerException`
This may be something else that is keeping you from connecting. I don't know what is causing it though.

**Comment by mrapplexz** [comment]
@mezz I'm uninstalled EnderIO, EnderCore, Agricultural Expansion and I still can't log in. My log now: [click](http://pastebin.com/TDq9Wh5M).

**Comment by mrapplexz** [comment]
@mezz Maybe JEI loads all the recipes in world load or server join event? Can you make config option "Load recipes after starting Minecraft"?

**Comment by Saereth** [comment]
I'm having the same issue on a custom 1.10.2 pack. Without JEI we can connect fine, as soon as JEI is added to the server everyone starts timing out on connect. Here is a clientside log if it helps:
http://paste.ee/p/cz5Za

running JEI version 3.12.8.325
Forge version 1.10.2 - 12.18.2.2107
about 116 mods in the pack, no Minetweaker scripting at all (yet). [Modlist](https://github.com/breakinblocks/nutsandbolts2/blob/master/CurrentModlist.txt)

Also tried with JEI version 3.12.8.326, same thing

**Comment by mezz** [comment]
Yes, that is the same problem.

Your JEI startup is taking about 42 seconds, and the Minecraft server disconnects you after not responding for 30 seconds.
I think it's safe to assume it has something to do with GregTech adding an insane amount of items and recipes.

I'm working on a clean solution for this in Minecraft 1.11, but maybe I can create a partial solution sooner.
Is there somewhere I can download your pack for testing?

**Comment by Saereth** [comment]
sure, here is the multimc instance, although you'll need to update jei to the latest to connect to the server, which im sure you have available :p https://dl.dropboxusercontent.com/u/28829658/NutsandBolts2v1a.zip

**Comment by mezz** [comment]
So uh... this pack is incredibly slow. #blameGregtech
I'll see what I can do.

**Comment by Saereth** [comment]
It is, especially first launch yeah greg lol

**Comment by mezz** [comment]
Status report:

I have a fix for this but it was breaking Reliquary and JER.
The issues for those are here:
https://github.com/P3pp3rF1y/Reliquary/issues/180
https://github.com/way2muchnoise/JustEnoughResources/pull/86

Once they are both fixed, I can update JEI and it will load everything during PostInit instead of when the player joins the world, so there will be no risk of timing out.

**Comment by mezz** [comment]
Fixed by https://github.com/mezz/JustEnoughItems/commit/85b4c51ba6b5837642b40ff1bf804cf547404f94
Available in JEI version 3.13.0.

**Comment by Gaelan** [comment]
Literally just ran into this. What timing!

**Comment by NitroxydeX** [comment]
I ran into this problem today with a modpack from curse. It already uses 3.13.3 but this problem still happens. It loads the recipes during Server Join Event.

**Comment by morrissimo** [comment]
Yeah, still seeing this behavior (~25s startup times for JEI) connecting to a brand new Infinity Lite server :/

**Comment by mezz** [comment]
Some time soon I intend to make it so that mods can't restart JEI when the game is connected to a server.
This will fix the problem for now.

I gave these mods some fair warning but it still seems to be an issue, so I have to take this action unfortunately.
Mods that really need to restart JEI for some reason can work with me to improve the API and make the function they need possible.

**Comment by morrissimo** [comment]
Thanks for the follow up @mezz! I did try connecting with the same modpack but on a much newer/faster computer and didn't have any noticeable issues - so def take that into consideration.
