### ISSUE TITLE
[Bug]: Failed to encode packet 'clientbound/minecraft:custom_payload' (jei:cheat_permission)

### ISSUE THREAD

**Issue by PsYchitOut** [mezz/JustEnoughItems#3614]
### Steps to Reproduce the Bug

Login to your own personal Minecraft Dedicated server that has the same version of JEI installed.

CTRL+Click for cheat mode.

be booted to menu with this message "Connection Lost Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (jei:cheat_permission)

### Expected Behavior

I would imagine I get a message stating I'm in cheat mode. I am OP and when I log back in cheat mode works just fine

### Actual Behavior

I get booted to menu with an error. if I am not OP I receive the correct message.

### Extra Notes (Optional)

I originally tried to post this as a crash, but given technically nothing crashed there is no crash log.

The log I gave you has other mods loaded but I have tested it with a instance that had only fabric, the API, and Just JEI with no plugins loaded and had the exact same results.

Also dunno if its useful but here is the server log from the moment I crash out.

19.07 17:25:50 [Server] Netty Epoll Server IO #6/ERROR Error sending packet clientbound/minecraft:custom_payload
19.07 17:25:50 [Server] INFO io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (jei:cheat_permission)
19.07 17:25:50 [Server] INFO at net.minecraft.class_9136.handler$zek000$fabric-networking-api-v1$encode(class_9136.java:547) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
19.07 17:25:50 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
19.07 17:26:10 [Multicraft] Skipped 17 lines due to rate limit (30/s)

### latest.log

https://gist.github.com/PsYchitOut/57e01a67ed2b7aaf6e7dd5833269a196.js

**Comment by yoyowoscar** [comment]
Pardon, will use the older version of JEI useful for this error?
I'm experiencing the same problem

**Comment by mezz** [comment]
Thanks for the report!
I have fixed this in https://github.com/mezz/JustEnoughItems/issues/3618

**Comment by blainegrissom** [comment]
Hello, I'd like to comment that I am still having this issue in Fabric 1.21, on JEI v19.5.3.67. I am OP in my server, and this is only a problem for me when in my server, not in singleplayer. 

[My logs specify that this is caused by a ClassCastException. Here is the gist.](https://gist.github.com/blainegrissom/8845aebd2819616e563bd34ed66b3aee)

**Comment by mezz** [comment]
Thanks for the report!
Does this happen if only JEI is installed, without other mods?

**Comment by mpalarie** [comment]
Been having the same issue for months on fabric. Currently on jei-1.21-fabric-19.5.3.70.jar. Issue only persists on home dedicated server, single player is fine. Any help would be greatly appreciated.

**Comment by mpalarie** [comment]
> The log I gave you has other mods loaded but I have tested it with a instance that had only fabric, the API, and Just JEI with no plugins loaded and had the exact same results.

**Comment by mezz** [comment]
Thank you for letting me know, I have tested it out and confirmed the bug. 
I pushed a fix for Fabric in the next version, and it will be available shortly.

**Comment by TheYmirsCla** [comment]
I'm having this issuse on a Purpur server with 30 plugins

**Comment by MaxTallOfficial** [comment]
Error is not fixed (
