### ISSUE TITLE
[Bug]: Drop chances, other tooltips not being shown in JEI

### ISSUE THREAD

**Issue by muggleorwizard** [mezz/JustEnoughItems#3683]
### Steps to Reproduce the Bug

Install a mod that shows drop chances of items (Ex Deorum for sieve drop rates, Botany Pots for soil rates, etc). 

### Expected Behavior

The drop rate should show. Function was present in earlier versions of JEI, affected mods have not updated. Confirmed feature not present in Ex Deorum and Botany Pots, although features were present in earlier versions of JEI. 

### Actual Behavior

Hover over items, no percent chance shown.

### Mod Pack URL (Optional)

https://legacy.curseforge.com/minecraft/modpacks/ozone-skyblock-reborn

### Mod Pack Version (Optional)

1.9.5

### Extra Notes (Optional)

thedarkcolour/ExDeorum#108

**Comment by mezz** [comment]
Thanks for the report!
Please try the latest version of JEI, I fixed some tooltip-related code the other day.

**Comment by muggleorwizard** [comment]
> Thanks for the report! Please try the latest version of JEI, I fixed some tooltip-related code the other day.

Still no luck on latest version, 15.12.2.51
![image](https://github.com/user-attachments/assets/8a1c1bae-606d-4908-8651-49a1262e5c10)

**Comment by mezz** [comment]
Thanks for checking!
I was able to replicate the bug with Ex Deorum and resolve the issue in `15.12.2.52`.

![Screenshot 2024-08-14 at 5 27 01 PM](https://github.com/user-attachments/assets/ec9d6c29-ae6e-4db5-97f9-969280bbce4a)

**Comment by muggleorwizard** [comment]
Thanks mezz!
