### ISSUE TITLE
[Bug]: Netherite upgrade recipe in smithing table not displaying correctly

### ISSUE THREAD

**Issue by jacopobono8** [mezz/JustEnoughItems#3693]
### Steps to Reproduce the Bug

1. Left click a netherite item in JEI menu.
2. Select the smithing table.
3. Search the recipe with the netherite upgrade smithing template (if the item is an armor).
4. Recipe shown is wrong.

### Expected Behavior

It should show the smithing template in the first slot, the diamond item in the second, the netherite ingot in the third, and the netherite item to the right of the arrow.
![2024-08-17_17 42 56](https://github.com/user-attachments/assets/78a4e1bb-aac2-4dfa-a3c2-1e8a6ed9690c)

### Actual Behavior

It show the netherite item in the second slot.
![2024-08-17_17 34 25](https://github.com/user-attachments/assets/77e07657-c4fd-4dd8-9a26-9df87b8c3b22)
![2024-08-17_17 34 19](https://github.com/user-attachments/assets/8e151c01-1240-405c-bd59-8c6ee77346fc)

### Extra Notes (Optional)

If you right click the netherite upgrade smithing template in JEI menu and click on the smithing table, the recipes shown are correct.
![2024-08-17_17 34 35](https://github.com/user-attachments/assets/8bbee92b-52df-452c-969b-4fa818f71f6c)

The version of Minecraft, Forge and JEI that I'm playing are respectively 1.20.1, 47.3.0 and 15.12.3.54.

### latest.log

https://gist.github.com/jacopobono8/7f1d4424c9693fa6db8fdbb5c357093c

**Comment by jimerrills** [comment]
I am having the same issue.

**Comment by PinkLasagna03** [comment]
I'm having the same issue, also with lots of other modded smithing recipes

**Comment by Luningor** [comment]
More on this: If you check the uses of the upgrade material (in this case netherite) the recipes show correctly, but otherwise they show up like this

**Comment by GLMaster19** [comment]
Having the same issue.
At the beginning thought that there is some mod conflicts. But, after similar tests, I think that this more related to JEI.

**Comment by mezz** [comment]
Thanks for the report!
I have pushed a fix for this in 1.21.1 and will backport it some time soon.

**Comment by jacopobono8** [comment]
> Thanks for the report!
> I have pushed a fix for this in 1.21.1 and will backport it some time soon.

Great. Thanks for the fix.

**Comment by Mitchell5200** [comment]
Still getting this with JEI 15.14.0.64, and Forge 47.3.6 and .7

**Comment by mezz** [comment]
This was fixed in 1.21.1 a while ago.
I backported the fix to 1.20.1 yesterday.
