### ISSUE TITLE
[1.10.2] [Bug] Recipe transfer to brewing stands unbrews potions

### ISSUE THREAD

**Issue by Dijkstra1-zz** [mezz/JustEnoughItems#419]
When i transfer items to the brewing with JEI plus, to put items into the brewer and if there already potions in there, it will put water bottle in your inventory instead of the potion that was in the brewing stand.

**Comment by Dijkstra1-zz** [comment]
[Here](https://github.com/mezz/JustEnoughItems/files/459690/Minecraft.1.10.2.04_09_2016.23_48_55.zip) is a video i record some time ago about it, seeing you in meet you making reminded of it.

**Comment by mezz** [comment]
Thanks for the report!
I was not able to reproduce this on the latest version, it may have been fixed.
Please try with the latest version, jei_1.10.2-3.9.0.248

**Comment by Dijkstra1-zz** [comment]
I updated my pack, but that did help they are only jei_1.10.2-3.9.0.247 (Bug still occurs), will update JEI manually.

**Comment by Dijkstra1-zz** [comment]
@mezz I have god news and I have bad new, the bad news is still happening in jei_1.10.2-3.9.0.248, good news think I know what is causing my guess is that it is syncing issue, and the reason that you have not been able reproduce, is because you have only tested it single player world, and in single it does move the potions with out unbrewing, only problem is here is it puts on of the potions in the blaze power slot, but on a multi player world, I get as in the video. Also while testing this have found that JEI does recognize water bottles for making awkward potion.

**Comment by VT-14** [comment]
I can confirm this Bug.
Just Enough Items: 1.10.2-3.9.3.253
Forge: 1.10.2-12.18.1.2087
No other mods.  Server was run on my computer.

Tested by placing 3 potions of Fire Resistance in a brewing stand, and having 3 water bottles and a piece of netherwart in my inventory, and using the recipe transfer for awkward potion.  No blaze powder was in the brewing stand, because I forgot it. Tests were done in creative mode, and all items were spawned in using JEI's cheat functionality.

Single Player - One potion is moved to the blaze powder slot, others are moved to the inventory.  They are still the potions that I stated out with (fire resistance).  The water bottles and netherwart are placed in the brewing stand as expected. Minor inconvenience, but not really an issue.

Server - Potions in brewing stand are turned into normal water bottles.  Water Bottles in inventory are untouched (no change in position).  Netherwart is moved into the correct slot. Re-logging did not fix this.  That is a bit of an issue.  Note that the relog test isn't included in the logs below.

Single Player Logs:
(General) Log: https://gist.github.com/VT-14/fc6606813a770bcfc3611901e76d5fdc
Manual Crash Log: https://gist.github.com/VT-14/03a5cfb678cd39571650787cdfd00194

Server Test Logs:
Client Log: https://gist.github.com/VT-14/6122540f044deaa0b59c8cd1f3bbfe32
Server Log: https://gist.github.com/VT-14/5a60cc7d1c33a567f184bbb98f48889f
Server's "latest": https://gist.github.com/VT-14/f86a04510f6dfaa1c248597fbc1a12fa

**Comment by mezz** [comment]
Thanks for confirming.
The blaze slot issue is easily fixed, it's an off-by-one error.
The potions are a bit more complicated. JEI has some extra information about potions that is available on the client but not the server, so the server ignored the difference between potions. It will take me a bit longer to solve this one properly.

**Comment by mezz** [comment]
Fixed both issues in JEI 3.9.4
