### ISSUE TITLE
[Bug]: 19.27.0.335 for NeoForge 1.21.1 cheat mode no longer turns the wrench icon red

### ISSUE THREAD

**Issue by Drawde2** [mezz/JustEnoughItems#4215]
### Steps to Reproduce the Bug

My keybind for cheat mode did nothing after updating to .335.  Ctrl-click on the wrench icon says cheat mode was enabled.  Changed the keybind and still nothing.  Restored to .334 and keybind worked again.

### Expected Behavior

Cheat mode turned on and off.

### Actual Behavior

Nothing happed.

**Comment by Drawde2** [comment]
I just learned that cheat mode does turn on, it just doesn't highlight this fact by turning the wrench icon in the corner red anymore so you know this.  You have to hover over the wrench icon to see this.

**Comment by mezz** [comment]
Thanks for the report!
I have fixed the bug here: https://github.com/mezz/JustEnoughItems/commit/f993bebb76c4d31a4b8e995b57a3492d1b067a6e
It's fixed in the latest version for 1.21.1 now.

**Comment by aminecraftplayerx** [comment]
As of version 19.27.0.337 this is still not working. (And it's driving me crazy!)
