### ISSUE TITLE
Latest version crashes on join with Refined Storage

### ISSUE THREAD

**Issue by SharkWipf** [mezz/JustEnoughItems#453]
Latest version (jei_1.10.2-3.11.0.269.jar) crashes on loading a world/joining a server with a Refined Storage error: [gist](https://gist.github.com/SharkWipf/547349efddd7ec1cce75c17aa49a3ccc)

Can be tested on custom [Blockheadism](https://minecraft.curseforge.com/projects/blockheadism) modpack v0.3.

EDIT: It did work with previous versions, can confirm rolling back just JEI fixes the issue.

**Comment by Unrepentant-Atheist** [comment]
Agreed: 
https://gist.github.com/anonymous/cb8837441b1016b602dbd14878cec5c8

**Comment by way2muchnoise** [comment]
Fixed in raoulvdberge/refinedstorage#385

**Comment by raoulvdberge** [comment]
Fixed for the next version

**Comment by mezz** [comment]
Thanks everyone!
This crash was from `RecipeWrapperSolderer extends VanillaRecipeWrapper`, since `VanillaRecipeWrapper` is an internal class that was removed.
This JEI update _should_ be backward compatible, so if you find anything that doesn't work please report :)

**Comment by way2muchnoise** [comment]
Yeah @mezz I also fixed that when I updated it :D

**Comment by mezz** [comment]
Yep, that's how I found the problem :). I went to look to confirm I didn't break the API somehow.
Don't forget to set `after:JEI@[3.11.0,);` in the dependencies string https://github.com/raoulvdberge/refinedstorage/blob/mc1.10/src/main/java/refinedstorage/RefinedStorage.java#L22

**Comment by Unrepentant-Atheist** [comment]
Nope, not fixed. Still crashing :P

https://gist.github.com/anonymous/a5e3c14cc38e5a2ed8d6580745842a1f

**Comment by mezz** [comment]
The fixed version has not been released yet.

**Comment by OldManCraft** [comment]
jei_1.10.2-3.11.1.275 Still has this issue.

**Comment by mezz** [comment]
The fixed version of Refined Storage has not been released yet.

**Comment by OldManCraft** [comment]
Ok Sorry...

**Comment by mezz** [comment]
You can use it with JEI 3.10 in the meantime, it should work fine.

**Comment by OldManCraft** [comment]
k Thank you..
