### ISSUE TITLE
Concurrent Modification Exception when joining world

### ISSUE THREAD

**Issue by brisingraerowing** [mezz/JustEnoughItems#493]
[Crash Report](https://gist.github.com/BrisingrAerowing/d4770240be2244bb68093e48d7e08708)

JEI 3.12.3.293
MC 1.10.2
Forge 2095

**Comment by mezz** [comment]
Thanks for the report!
Can you upload your full client log to gist? I need a bit more information to figure this one out.

**Comment by brisingraerowing** [comment]
Sure. Just let me figure out which window is the one I need (I have a very messy taskbar right now)

**Comment by brisingraerowing** [comment]
@mezz  Just added it.

**Comment by mezz** [comment]
Can you link it here? I think you made a private gist.

**Comment by way2muchnoise** [comment]
@raoulvdberge didn't you fix this?

**Comment by brisingraerowing** [comment]
I uploaded it to the original Gist as a second file.

**Comment by raoulvdberge** [comment]
I fixed this, and since I don't see RS in the stacktrace, I don't think this is a RS issue.

**Comment by mezz** [comment]
This looks like a different bug, yes. This is happening during JEI startup.

**Comment by mezz** [comment]
Ok here's what I know so far:
JEI is starting up twice, at the same time.

```
[17:03:30] [Server thread/INFO] [JEI/]: Beginning startup...
[17:03:30] [Client thread/INFO] [JEI/]: Beginning startup...
```

When the `infinitystorage` JEI integration crashes, JEI tries to remove it from the list of available plugins, but it does it on two different threads at the same time and causes it to crash.

I need to find out how or why JEI is starting on two different threads at the same time.
It should only be on the Client thread, not the Server thread, so I think some other mod is messing things up very badly.

**Comment by mezz** [comment]
@BrisingrAerowing Please try removing some of these coremods to see if one of them is causing the problem:

```
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  offlineskins (OfflineSkins-1.10.2-v1a.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  OFMDepLoader (OpenFM-1.9.4-0.1.0.11.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10.2-2.0.12.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  TNTUtilities Core (tnt_utilities-mc1.10-1.2.1.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.3.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.325.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
```

**Comment by mezz** [comment]
Got another crash log from @VapourDrive with Server and Client threads both starting JEI:
https://paste.ee/p/KJTyc

**Comment by ColinGBos** [comment]
My world now loads fine as soon as I remove EnderIO and EnderCore.

**Comment by mezz** [comment]
Thanks! EnderCore is in the first crash log as well, I'll look into it.

**Comment by mezz** [comment]
Talked to @HenryLoenwind and this is actually a JEI issue, caused by a race condition in the client and server threads. I didn't expect the server thread to be able to call my client proxy code, but it can on the integrated (single-player) client. Fix is coming shortly.

**Comment by ColinGBos** [comment]
Not sure if it's still helpful, but apparently the fewest number of mods I can get my game to crash with is just JEI, EIO, EnderCore and Tesla
https://paste.ee/p/PQ76T

**Comment by mezz** [comment]
Try version 3.12.5 (once it builds), it should be fixed now.

**Comment by ColinGBos** [comment]
build 497 still crashes, https://paste.ee/p/o1Y5Q
Just JEI, Tesla, EnderCore and EnderIO

**Comment by mezz** [comment]
That looks like a different bug. EnderIO is logging errors on JEI startup

```
[20:23:57] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[20:23:57] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[20:23:57] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:-1]:  ... 43 more
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyConnection
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.ClassLoader.loadClass(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.Class.forName0(Native Method)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.Class.forName(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at crazypants.enderio.tool.EnderIOCrashCallable.rfDiagnostics(EnderIOCrashCallable.java:179)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at crazypants.enderio.tool.EnderIOCrashCallable.call(EnderIOCrashCallable.java:123)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at crazypants.enderio.tool.EnderIOCrashCallable.call(EnderIOCrashCallable.java:17)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraftforge.fml.common.FMLCommonHandler.enhanceCrashReport(FMLCommonHandler.java:377)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:117)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.crash.CrashReport.<init>(CrashReport.java:38)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:122)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.world.World.func_72838_d(World.java:1129)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.client.main.Main.main(SourceFile:124)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at java.lang.reflect.Method.invoke(Unknown Source)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:191)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at org.multimc.EntryPoint.listen(EntryPoint.java:162)
[20:23:57] [Client thread/INFO]: [crazypants.enderio.tool.EnderIOCrashCallable:rfDiagnostics:183]:  at org.multimc.EntryPoint.main(EntryPoint.java:53)
```

**Comment by HenryLoenwind** [comment]
Are you sure this isn't caused by having 2 different Baubles jars installed or by Tesla missing half its classes?

**Comment by HenryLoenwind** [comment]
The EnderIOCrashCallable:rfDiagnostics output is normal when there's no RF API installed. I should probably reduce that spam now that RF is no longer shipped with Ender IO ;)

**Comment by ColinGBos** [comment]
Heh, might be Baubles >.> Damn lib's getting thrown in subfolders.
