### ISSUE TITLE
crash while loading world

### ISSUE THREAD

**Issue by 0Navis0** [mezz/JustEnoughItems#558]
I get a crash with the new JEI version when I try to load a world. There is no any crash report generated and Minecraft doesn't crash, it just freezes at the world loading. I get that in the log : http://pastebin.com/AJV2Jk6t

**Comment by jsaggers** [comment]
I also have the same issue (The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.) just sits there, have gone back a build of JEI and all is good.

**Comment by GirafiStudios** [comment]
I can confirm that this only happens with 3.13.339. Although something that is not already mentioned here is that it only happens with CraftTweaker installed - also with no scripts running.

**Comment by mezz** [comment]
Thanks for the report!
Fixing it now, it has to do with my progress bar hack from today.

**Comment by mezz** [comment]
This should be fixed in JEI 3.13.0.340, please let me know if it works for you.

**Comment by b0bst3r** [comment]
Still happening http://pastebin.ubuntu.com/23414552/ line 6275 seems to be causing modtweaker and CraftTweaker to error.

There's also a crash at line 2912 but think this is probably JER issue but it's non-fatal.

**Comment by mezz** [comment]
Thanks, try JEI 341 once it's built.

**Comment by mezz** [comment]
Available here now https://dvs1.progwml6.com/jenkins/job/JustEnoughItems/

**Comment by GirafiStudios** [comment]
Can confirm it is fixed in 341.

**Comment by mezz** [comment]
Thanks, please let me know if you see any new problems with the loading screen.
