### ISSUE TITLE
Crash when looking through recipes (1.11.2)

### ISSUE THREAD

**Issue by DeeDoubleYous** [mezz/JustEnoughItems#863]
I was looking through the uses for slime balls with the version 4.3.6.279 of jei when, I crashed with this crash log.
https://pastebin.com/PHpymy8t

**Comment by mezz** [comment]
Thanks for the report!

**Comment by Yarden-zamir** [comment]
Yea, i have that problem too

**Comment by mezz** [comment]
This has been fixed in the latest version.

**Comment by Yarden-zamir** [comment]
it still crashes on the latest version, rolling two versions back solves it for now until you find the source

**Comment by Yarden-zamir** [comment]
is the fix only for the 1.11 build? and if so, can you roll it for the 1.10 too?

**Comment by mezz** [comment]
Yes this fix is for 1.11. If you are crashing in 1.10 please link your crash log so I can look into it.

**Comment by Yarden-zamir** [comment]
I [did](https://github.com/mezz/JustEnoughItems/issues/881)
